### ISSUE TITLE
tox -e py27-ptlatest-x hangs and eats all memory

### ISSUE THREAD

**Issue by The-Compiler** [gocept/pytest-rerunfailures#24]
I previously raised this at https://github.com/davehunt/pytest-html/issues/31 but I can reproduce this with rerunfailures' testsuite as well. When running `tox -e py27-ptlatest-x`, after about a minute, the tests eat up 10 GB of RAM and fail spectacularly with >15000 lines of output:

```
GLOB sdist-make: /home/florian/proj/pytest-rerunfailures/setup.py
py27-ptlatest-x recreate: /home/florian/proj/pytest-rerunfailures/.tox/py27-ptlatest-x
py27-ptlatest-x installdeps: pytest, pytest-xdist
py27-ptlatest-x inst: /home/florian/proj/pytest-rerunfailures/.tox/dist/pytest-rerunfailures-0.05.zip
py27-ptlatest-x runtests: PYTHONHASHSEED='4015671028'
py27-ptlatest-x runtests: commands[0] | /home/florian/proj/pytest-rerunfailures/.tox/py27-ptlatest-x/bin/py.test .
============================= test session starts ==============================
platform linux2 -- Python 2.7.9, pytest-2.8.7, py-1.4.31, pluggy-0.3.1
rootdir: /home/florian/proj/pytest-rerunfailures, inifile: 
plugins: rerunfailures-0.05, xdist-1.13.1
collected 20 items

tests/test_config.py xs
tests/test_functionality.py ...............F.F

=================================== FAILURES ===================================
_____________ TestFunctionality.test_verbose_statuses_with_reruns ______________

self = <test_functionality.TestFunctionality object at 0x7f8c0e4e4e10>
testdir = <Testdir local('/tmp/pytest-of-florian/pytest-16/testdir/test_verbose_statuses_with_reruns0')>

    def test_verbose_statuses_with_reruns(self, testdir):
        test_file = self.variety_of_tests(testdir)
    
        result = testdir.runpytest('--reruns=2', '--verbose')
    
        assert self._substring_in_output(' 1 passed', result.outlines)
>       assert self._substring_in_output('test_verbose_statuses_with_reruns.py:3: test_fake_pass PASSED', result.outlines)
E       assert <bound method TestFunctionality._substring_in_output of <test_functionality.TestFunctionality object at 0x7f8c0e4e4e10>>('test_verbose_statuses_with_reruns.py:3: test_fake_pass PASSED', ['============================= test session starts ==============================', 'platform linux2 -- Python 2.7.9,...tatuses_with_reruns0, inifile: ', 'plugins: rerunfailures-0.05, xdist-1.13.1', 'collecting ... collected 5 items', ...])
E        +  where <bound method TestFunctionality._substring_in_output of <test_functionality.TestFunctionality object at 0x7f8c0e4e4e10>> = <test_functionality.TestFunctionality object at 0x7f8c0e4e4e10>._substring_in_output
E        +  and   ['============================= test session starts ==============================', 'platform linux2 -- Python 2.7.9,...tatuses_with_reruns0, inifile: ', 'plugins: rerunfailures-0.05, xdist-1.13.1', 'collecting ... collected 5 items', ...] = <_pytest.pytester.RunResult instance at 0x7f8c0e99c488>.outlines

/home/florian/proj/pytest-rerunfailures/tests/test_functionality.py:296: AssertionError
----------------------------- Captured stdout call -----------------------------
============================= test session starts ==============================
platform linux2 -- Python 2.7.9, pytest-2.8.7, py-1.4.31, pluggy-0.3.1 -- /home/florian/proj/pytest-rerunfailures/.tox/py27-ptlatest-x/bin/python2.7
cachedir: .cache
rootdir: /tmp/pytest-of-florian/pytest-16/testdir/test_verbose_statuses_with_reruns0, inifile: 
plugins: rerunfailures-0.05, xdist-1.13.1
collecting ... collected 5 items

test_verbose_statuses_with_reruns.py::test_fake_pass PASSED
test_verbose_statuses_with_reruns.py::test_fake_fail FAILED
test_verbose_statuses_with_reruns.py::test_xfail xfail
test_verbose_statuses_with_reruns.py::test_xpass XPASS
test_verbose_statuses_with_reruns.py::test_flaky_test RERUN

=================================== FAILURES ===================================
________________________________ test_fake_fail ________________________________

    @pytest.mark.nondestructive
    def test_fake_fail():
>       raise Exception, "OMG! fake test failure!"
E       Exception: OMG! fake test failure!

test_verbose_statuses_with_reruns.py:9: Exception
====== 1 failed, 1 passed, 1 xfailed, 1 xpassed, 1 rerun in 0.02 seconds =======
------------------------------
' 1 passed' matched: ====== 1 failed, 1 passed, 1 xfailed, 1 xpassed, 1 rerun in 0.02 seconds =======
------------------------------
'test_verbose_statuses_with_reruns.py:3: test_fake_pass PASSED' not found in:
	============================= test session starts ==============================
	platform linux2 -- Python 2.7.9, pytest-2.8.7, py-1.4.31, pluggy-0.3.1 -- /home/florian/proj/pytest-rerunfailures/.tox/py27-ptlatest-x/bin/python2.7
	cachedir: .cache
	rootdir: /tmp/pytest-of-florian/pytest-16/testdir/test_verbose_statuses_with_reruns0, inifile: 
	plugins: rerunfailures-0.05, xdist-1.13.1
	collecting ... collected 5 items
	
	test_verbose_statuses_with_reruns.py::test_fake_pass PASSED
	test_verbose_statuses_with_reruns.py::test_fake_fail FAILED
	test_verbose_statuses_with_reruns.py::test_xfail xfail
	test_verbose_statuses_with_reruns.py::test_xpass XPASS
	test_verbose_statuses_with_reruns.py::test_flaky_test RERUN
	
	=================================== FAILURES ===================================
	________________________________ test_fake_fail ________________________________
	
	    @pytest.mark.nondestructive
	    def test_fake_fail():
	>       raise Exception, "OMG! fake test failure!"
	E       Exception: OMG! fake test failure!
	
	test_verbose_statuses_with_reruns.py:9: Exception
	====== 1 failed, 1 passed, 1 xfailed, 1 xpassed, 1 rerun in 0.02 seconds =======
	
___________ TestFunctionality.test_report_on_with_reruns_with_xdist ____________

self = <test_functionality.TestFunctionality object at 0x7f8c0e677650>
testdir = <Testdir local('/tmp/pytest-of-florian/pytest-16/testdir/test_report_on_with_reruns_with_xdist0')>

    def test_report_on_with_reruns_with_xdist(self, testdir):
        '''This test is identical to test_report_on_with_reruns except it
            also uses xdist's -n flag.
            '''
        # precondition: xdist installed
        self._pytest_xdist_installed(testdir)
    
        test_file = self.variety_of_tests(testdir)
    
        result = testdir.runpytest('--reruns=2', '-r fsxXR', '-n 1')
    
>       assert self._substring_in_output('.FxXR', result.outlines)
E       assert <bound method TestFunctionality._substring_in_output of <test_functionality.TestFunctionality object at 0x7f8c0e677650>>('.FxXR', ['============================= test session starts ==============================', 'platform linux2 -- Python 2.7.9,...e: ', 'plugins: rerunfailures-0.05, xdist-1.13.1', 'gw0 I', '[gw0] node down: Traceback (most recent call last):', ...])
E        +  where <bound method TestFunctionality._substring_in_output of <test_functionality.TestFunctionality object at 0x7f8c0e677650>> = <test_functionality.TestFunctionality object at 0x7f8c0e677650>._substring_in_output
E        +  and   ['============================= test session starts ==============================', 'platform linux2 -- Python 2.7.9,...e: ', 'plugins: rerunfailures-0.05, xdist-1.13.1', 'gw0 I', '[gw0] node down: Traceback (most recent call last):', ...] = <_pytest.pytester.RunResult instance at 0x7f8c0e5bca28>.outlines

/home/florian/proj/pytest-rerunfailures/tests/test_functionality.py:348: AssertionError
----------------------------- Captured stdout call -----------------------------
============================= test session starts ==============================
platform linux2 -- Python 2.7.9, pytest-2.8.7, py-1.4.31, pluggy-0.3.1
rootdir: /tmp/pytest-of-florian/pytest-16/testdir/test_report_on_with_reruns_with_xdist0, inifile: 
plugins: rerunfailures-0.05, xdist-1.13.1
gw0 I
[gw0] node down: Traceback (most recent call last):
  File "/home/florian/proj/pytest-rerunfailures/.tox/py27-ptlatest-x/local/lib/python2.7/site-packages/execnet/gateway_base.py", line 841, in _local_receive
    data = loads_internal(data, channel, strconfig)
  File "/home/florian/proj/pytest-rerunfailures/.tox/py27-ptlatest-x/local/lib/python2.7/site-packages/execnet/gateway_base.py", line 1350, in loads_internal
    return Unserializer(io, channelfactory, strconfig).load()
  File "/home/florian/proj/pytest-rerunfailures/.tox/py27-ptlatest-x/local/lib/python2.7/site-packages/execnet/gateway_base.py", line 1152, in load
    opcode = self.stream.read(1)
  File "/usr/lib/python2.7/StringIO.py", line 127, in read
    _complain_ifclosed(self.closed)
TypeError: 'NoneType' object is not callable

Replacing crashed slave gw0
[gw1] node down: Traceback (most recent call last):

[...]

Replacing crashed slave gw290
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/florian/proj/pytest-rerunfailures/.tox/py27-ptlatest-x/local/lib/python2.7/site-packages/_pytest/main.py", line 90, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/home/florian/proj/pytest-rerunfailures/.tox/py27-ptlatest-x/local/lib/python2.7/site-packages/_pytest/main.py", line 121, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/home/florian/proj/pytest-rerunfailures/.tox/py27-ptlatest-x/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 724, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/home/florian/proj/pytest-rerunfailures/.tox/py27-ptlatest-x/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/florian/proj/pytest-rerunfailures/.tox/py27-ptlatest-x/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 301, in __call__
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/florian/proj/pytest-rerunfailures/.tox/py27-ptlatest-x/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 279, in get_result
INTERNALERROR>     _reraise(*ex)  # noqa
INTERNALERROR>   File "/home/florian/proj/pytest-rerunfailures/.tox/py27-ptlatest-x/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 264, in __init__
INTERNALERROR>     self.result = func()
INTERNALERROR>   File "/home/florian/proj/pytest-rerunfailures/.tox/py27-ptlatest-x/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 299, in <lambda>
INTERNALERROR>     outcome = _CallOutcome(lambda: self.oldcall(hook, hook_impls, kwargs))
INTERNALERROR>   File "/home/florian/proj/pytest-rerunfailures/.tox/py27-ptlatest-x/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 333, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "/home/florian/proj/pytest-rerunfailures/.tox/py27-ptlatest-x/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 596, in execute
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/florian/proj/pytest-rerunfailures/.tox/py27-ptlatest-x/local/lib/python2.7/site-packages/xdist/dsession.py", line 521, in pytest_runtestloop
INTERNALERROR>     self.loop_once()
INTERNALERROR>   File "/home/florian/proj/pytest-rerunfailures/.tox/py27-ptlatest-x/local/lib/python2.7/site-packages/xdist/dsession.py", line 539, in loop_once
INTERNALERROR>     call(**kwargs)
INTERNALERROR>   File "/home/florian/proj/pytest-rerunfailures/.tox/py27-ptlatest-x/local/lib/python2.7/site-packages/xdist/dsession.py", line 603, in slave_errordown
INTERNALERROR>     self._clone_node(node)
INTERNALERROR>   File "/home/florian/proj/pytest-rerunfailures/.tox/py27-ptlatest-x/local/lib/python2.7/site-packages/xdist/dsession.py", line 665, in _clone_node
INTERNALERROR>     node = self.nodemanager.setup_node(spec, self.queue.put)
INTERNALERROR>   File "/home/florian/proj/pytest-rerunfailures/.tox/py27-ptlatest-x/local/lib/python2.7/site-packages/xdist/slavemanage.py", line 49, in setup_node
INTERNALERROR>     gw = self.group.makegateway(spec)
INTERNALERROR>   File "/home/florian/proj/pytest-rerunfailures/.tox/py27-ptlatest-x/local/lib/python2.7/site-packages/execnet/multi.py", line 127, in makegateway
INTERNALERROR>     io = gateway_io.create_io(spec, execmodel=self.execmodel)
INTERNALERROR>   File "/home/florian/proj/pytest-rerunfailures/.tox/py27-ptlatest-x/local/lib/python2.7/site-packages/execnet/gateway_io.py", line 113, in create_io
INTERNALERROR>     return Popen2IOMaster(args, execmodel)
INTERNALERROR>   File "/home/florian/proj/pytest-rerunfailures/.tox/py27-ptlatest-x/local/lib/python2.7/site-packages/execnet/gateway_io.py", line 17, in __init__
INTERNALERROR>     self.popen = p = execmodel.PopenPiped(args)
INTERNALERROR>   File "/home/florian/proj/pytest-rerunfailures/.tox/py27-ptlatest-x/local/lib/python2.7/site-packages/execnet/gateway_base.py", line 178, in PopenPiped
INTERNALERROR>     return self.subprocess.Popen(args, stdout=PIPE, stdin=PIPE)
INTERNALERROR>   File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
INTERNALERROR>     errread, errwrite)
INTERNALERROR>   File "/usr/lib/python2.7/subprocess.py", line 1231, in _execute_child
INTERNALERROR>     self.pid = os.fork()
INTERNALERROR> OSError: [Errno 12] Cannot allocate memory

======================== no tests ran in 65.22 seconds =========================
------------------------------
'.FxXR' not found in:
	============================= test session starts ==============================
	platform linux2 -- Python 2.7.9, pytest-2.8.7, py-1.4.31, pluggy-0.3.1
	rootdir: /tmp/pytest-of-florian/pytest-16/testdir/test_report_on_with_reruns_with_xdist0, inifile: 
	plugins: rerunfailures-0.05, xdist-1.13.1
	gw0 I
	[gw0] node down: Traceback (most recent call last):
	  File "/home/florian/proj/pytest-rerunfailures/.tox/py27-ptlatest-x/local/lib/python2.7/site-packages/execnet/gateway_base.py", line 841, in _local_receive
	    data = loads_internal(data, channel, strconfig)
	  File "/home/florian/proj/pytest-rerunfailures/.tox/py27-ptlatest-x/local/lib/python2.7/site-packages/execnet/gateway_base.py", line 1350, in loads_internal
	    return Unserializer(io, channelfactory, strconfig).load()
	  File "/home/florian/proj/pytest-rerunfailures/.tox/py27-ptlatest-x/local/lib/python2.7/site-packages/execnet/gateway_base.py", line 1152, in load
	    opcode = self.stream.read(1)
	  File "/usr/lib/python2.7/StringIO.py", line 127, in read
	    _complain_ifclosed(self.closed)
	TypeError: 'NoneType' object is not callable
	
	Replacing crashed slave gw0

[...]

	Replacing crashed slave gw290
	INTERNALERROR> Traceback (most recent call last):
	INTERNALERROR>   File "/home/florian/proj/pytest-rerunfailures/.tox/py27-ptlatest-x/local/lib/python2.7/site-packages/_pytest/main.py", line 90, in wrap_session
	INTERNALERROR>     session.exitstatus = doit(config, session) or 0
	INTERNALERROR>   File "/home/florian/proj/pytest-rerunfailures/.tox/py27-ptlatest-x/local/lib/python2.7/site-packages/_pytest/main.py", line 121, in _main
	INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
	INTERNALERROR>   File "/home/florian/proj/pytest-rerunfailures/.tox/py27-ptlatest-x/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 724, in __call__
	INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
	INTERNALERROR>   File "/home/florian/proj/pytest-rerunfailures/.tox/py27-ptlatest-x/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec
	INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
	INTERNALERROR>   File "/home/florian/proj/pytest-rerunfailures/.tox/py27-ptlatest-x/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 301, in __call__
	INTERNALERROR>     return outcome.get_result()
	INTERNALERROR>   File "/home/florian/proj/pytest-rerunfailures/.tox/py27-ptlatest-x/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 279, in get_result
	INTERNALERROR>     _reraise(*ex)  # noqa
	INTERNALERROR>   File "/home/florian/proj/pytest-rerunfailures/.tox/py27-ptlatest-x/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 264, in __init__
	INTERNALERROR>     self.result = func()
	INTERNALERROR>   File "/home/florian/proj/pytest-rerunfailures/.tox/py27-ptlatest-x/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 299, in <lambda>
	INTERNALERROR>     outcome = _CallOutcome(lambda: self.oldcall(hook, hook_impls, kwargs))
	INTERNALERROR>   File "/home/florian/proj/pytest-rerunfailures/.tox/py27-ptlatest-x/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 333, in <lambda>
	INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
	INTERNALERROR>   File "/home/florian/proj/pytest-rerunfailures/.tox/py27-ptlatest-x/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 596, in execute
	INTERNALERROR>     res = hook_impl.function(*args)
	INTERNALERROR>   File "/home/florian/proj/pytest-rerunfailures/.tox/py27-ptlatest-x/local/lib/python2.7/site-packages/xdist/dsession.py", line 521, in pytest_runtestloop
	INTERNALERROR>     self.loop_once()
	INTERNALERROR>   File "/home/florian/proj/pytest-rerunfailures/.tox/py27-ptlatest-x/local/lib/python2.7/site-packages/xdist/dsession.py", line 539, in loop_once
	INTERNALERROR>     call(**kwargs)
	INTERNALERROR>   File "/home/florian/proj/pytest-rerunfailures/.tox/py27-ptlatest-x/local/lib/python2.7/site-packages/xdist/dsession.py", line 603, in slave_errordown
	INTERNALERROR>     self._clone_node(node)
	INTERNALERROR>   File "/home/florian/proj/pytest-rerunfailures/.tox/py27-ptlatest-x/local/lib/python2.7/site-packages/xdist/dsession.py", line 665, in _clone_node
	INTERNALERROR>     node = self.nodemanager.setup_node(spec, self.queue.put)
	INTERNALERROR>   File "/home/florian/proj/pytest-rerunfailures/.tox/py27-ptlatest-x/local/lib/python2.7/site-packages/xdist/slavemanage.py", line 49, in setup_node
	INTERNALERROR>     gw = self.group.makegateway(spec)
	INTERNALERROR>   File "/home/florian/proj/pytest-rerunfailures/.tox/py27-ptlatest-x/local/lib/python2.7/site-packages/execnet/multi.py", line 127, in makegateway
	INTERNALERROR>     io = gateway_io.create_io(spec, execmodel=self.execmodel)
	INTERNALERROR>   File "/home/florian/proj/pytest-rerunfailures/.tox/py27-ptlatest-x/local/lib/python2.7/site-packages/execnet/gateway_io.py", line 113, in create_io
	INTERNALERROR>     return Popen2IOMaster(args, execmodel)
	INTERNALERROR>   File "/home/florian/proj/pytest-rerunfailures/.tox/py27-ptlatest-x/local/lib/python2.7/site-packages/execnet/gateway_io.py", line 17, in __init__
	INTERNALERROR>     self.popen = p = execmodel.PopenPiped(args)
	INTERNALERROR>   File "/home/florian/proj/pytest-rerunfailures/.tox/py27-ptlatest-x/local/lib/python2.7/site-packages/execnet/gateway_base.py", line 178, in PopenPiped
	INTERNALERROR>     return self.subprocess.Popen(args, stdout=PIPE, stdin=PIPE)
	INTERNALERROR>   File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
	INTERNALERROR>     errread, errwrite)
	INTERNALERROR>   File "/usr/lib/python2.7/subprocess.py", line 1231, in _execute_child
	INTERNALERROR>     self.pid = os.fork()
	INTERNALERROR> OSError: [Errno 12] Cannot allocate memory
	
	======================== no tests ran in 65.22 seconds =========================
	
----------------------------- Captured stderr call -----------------------------
This is pytest version 2.8.7, imported from /home/florian/proj/pytest-rerunfailures/.tox/py27-ptlatest-x/local/lib/python2.7/site-packages/pytest.pyc
setuptools registered plugins:
  pytest-rerunfailures-0.05 at /home/florian/proj/pytest-rerunfailures/.tox/py27-ptlatest-x/local/lib/python2.7/site-packages/rerunfailures/plugin.pyc
  pytest-xdist-1.13.1 at /home/florian/proj/pytest-rerunfailures/.tox/py27-ptlatest-x/local/lib/python2.7/site-packages/xdist/plugin.pyc
  pytest-xdist-1.13.1 at /home/florian/proj/pytest-rerunfailures/.tox/py27-ptlatest-x/local/lib/python2.7/site-packages/xdist/looponfail.pyc
  pytest-xdist-1.13.1 at /home/florian/proj/pytest-rerunfailures/.tox/py27-ptlatest-x/local/lib/python2.7/site-packages/xdist/boxed.pyc
nomatch: '*pytest-xdist*'
    and: u'This is pytest version 2.8.7, imported from /home/florian/proj/pytest-rerunfailures/.tox/py27-ptlatest-x/local/lib/python2.7/site-packages/pytest.pyc'
    and: u'setuptools registered plugins:'
    and: u'  pytest-rerunfailures-0.05 at /home/florian/proj/pytest-rerunfailures/.tox/py27-ptlatest-x/local/lib/python2.7/site-packages/rerunfailures/plugin.pyc'
fnmatch: '*pytest-xdist*'
   with: u'  pytest-xdist-1.13.1 at /home/florian/proj/pytest-rerunfailures/.tox/py27-ptlatest-x/local/lib/python2.7/site-packages/xdist/plugin.pyc'
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/florian/proj/pytest-rerunfailures/.tox/py27-ptlatest-x/local/lib/python2.7/site-packages/_pytest/main.py", line 90, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/home/florian/proj/pytest-rerunfailures/.tox/py27-ptlatest-x/local/lib/python2.7/site-packages/_pytest/main.py", line 120, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "/home/florian/proj/pytest-rerunfailures/.tox/py27-ptlatest-x/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 724, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/home/florian/proj/pytest-rerunfailures/.tox/py27-ptlatest-x/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/florian/proj/pytest-rerunfailures/.tox/py27-ptlatest-x/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 333, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "/home/florian/proj/pytest-rerunfailures/.tox/py27-ptlatest-x/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 596, in execute
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/florian/proj/pytest-rerunfailures/.tox/py27-ptlatest-x/local/lib/python2.7/site-packages/_pytest/main.py", line 129, in pytest_collection
INTERNALERROR>     return session.perform_collect()
INTERNALERROR>   File "/home/florian/proj/pytest-rerunfailures/.tox/py27-ptlatest-x/local/lib/python2.7/site-packages/_pytest/main.py", line 565, in perform_collect
INTERNALERROR>     hook.pytest_collection_finish(session=self)
INTERNALERROR>   File "/home/florian/proj/pytest-rerunfailures/.tox/py27-ptlatest-x/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 724, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/home/florian/proj/pytest-rerunfailures/.tox/py27-ptlatest-x/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/florian/proj/pytest-rerunfailures/.tox/py27-ptlatest-x/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 333, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "/home/florian/proj/pytest-rerunfailures/.tox/py27-ptlatest-x/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 596, in execute
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "<remote exec>", line 77, in pytest_collection_finish
INTERNALERROR>   File "<remote exec>", line 23, in sendevent
INTERNALERROR>   File "/home/florian/proj/pytest-rerunfailures/.tox/py27-ptlatest-x/local/lib/python2.7/site-packages/execnet/gateway_base.py", line 716, in send
INTERNALERROR>     raise IOError("cannot send to %r" % (self,))
INTERNALERROR> IOError: cannot send to <Channel id=1 closed>

[...]
```

**Comment by florianpilz** [comment]
@The-Compiler Could you please try again using the latest release? Core logic and `tox.ini` was largely rewritten.

**Comment by The-Compiler** [comment]
Thanks! I can confirm this is fixed in master, and pytest-html's test also work for me when using pytest-rerunfailures from git.
